### PR TITLE
Add coding style guide

### PR DESCRIPTION
**Pull request by mway**
This PR adds the M3 style guide, which is a superset of Uber's [Go Style Guide](https://github.com/uber-go/guide/blob/master/style.md) (that is, unless explicitly specified/overridden, M3 will follow Uber's style guide by default).

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
I have a writing style guide in progress too, so one tiny piece of feedback would be to update this to refer to a coding style guide.

**Comment by mway** [comment]
> I have a writing style guide in progress too, so one tiny piece of feedback would be to update this to refer to a coding style guide.

This is a coding style guide - it's an umbrella guide to add on top of the [Uber style guide](https://github.com/uber-go/guide/blob/master/style.md), which we're adopting here as well. Can you give some examples of what types of things you'd like to add guidance around? Happy to work with you to incorporate things into the Uber guide, or to add to this one.

**Comment by ChrisChinchilla** [comment]
> > I have a writing style guide in progress too, so one tiny piece of feedback would be to update this to refer to a coding style guide.
> 
> This is a coding style guide - it's an umbrella guide to add on top of the [Uber style guide](https://github.com/uber-go/guide/blob/master/style.md), which we're adopting here as well. Can you give some examples of what types of things you'd like to add guidance around? Happy to work with you to incorporate things into the Uber guide, or to add to this one.

I get that, but I'm asking that it's clearer in this doc that it's a coding style guide, at the moment it just says "style guide", basically just update the heading, add that in the opening paragraphs etc. That's about it, minor stuff I know, but just so when I add the written word style guide it's more obvious where people should look. It may be that when I add the written word style guide, some further tweaks will be needed, but I can handle that then :)

**Comment by mway** [comment]
> I get that, but I'm asking that it's clearer in this doc that it's a coding style guide, at the moment it just says "style guide", basically just update the heading, add that in the opening paragraphs etc. That's about it, minor stuff I know, but just so when I add the written word style guide it's more obvious where people should look. It may be that when I add the written word style guide, some further tweaks will be needed, but I can handle that then :)

Ah! Understood, my bad. I'll update this to be clearer. Thanks!

**Comment by ChrisChinchilla** [comment]
> Ah! Understood, my bad. I'll update this to be clearer. Thanks!

Amazing, thanks!

**Review by robskillington — APPROVED** [review]
LGTM, great!

**Pull request merged**
