### PR TITLE
Upgrade Go runtime to Go 1.16

### PR DESCRIPTION
**Pull request by robskillington**
**What this PR does / why we need it**:

Upgrades M3 to use Go 1.16.

This will require production testing which is ongoing.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing and/or backwards incompatible change?**:

```release-note
NONE
```

**Does this PR require updating code package or user-facing documentation?**:

```documentation-note
NONE
```

### CODE REVIEW

**Review by vdarulis — CHANGES_REQUESTED** [review]
Can you hold off onto this? This will also block anything using `m3db/m3` as a library due to `go.mod` requiring 1.16 as well.

**Comment by robskillington** [comment]
Potentially I can simply downgrade the `go.mod` @vdarulis but upgrade everything else in the build process?

**Comment by robskillington** [comment]
@vdarulis have reverted the go.mod but kept everything else (dockerfiles, CI, etc) at Go 1.16. 

Does this work for you folks?

**Comment by vdarulis** [comment]
> @vdarulis have reverted the go.mod but kept everything else (dockerfiles, CI, etc) at Go 1.16.
> 
> Does this work for you folks?

1.15 and below works, just that you'd have to also fiddle with build as all tools will reset this back to 1.16 and cause repo to be dirty after build.

**Review by vdarulis — APPROVED** [review]

**Pull request merged**
