### PR TITLE
[dbnode] Emit metric with dbnode health status

### PR DESCRIPTION
**Pull request by abliqo**
**Problem:**

In a large M3DB cluster, when a database node becomes non-functional (service fails to start or host is down), it may go unnoticed. If it goes unnoticed long enough, and one more node that owns the same shard(s) becomes non-functional, a quorum may be lost and block writes to the database.

**Solution:**

The connection pool in `src/dbnode/client/connection_pool.go` already does periodic health check from the client's node/process. Let that code emit a gauge with the result of health check. The metrics scope passed to `newConnectionPool` is already tagged with `hostID`.

Since the health check is done from the client, it implies that node is in M3DB placement and expected to be functional. Thus, alerting can be set up based on this metric alone.

**Considered Alternatives:**

1. Emit a heartbeat metric from `src/dbnode/network/server/tchannelthrift/node/service.go`. Alerting on lost heartbeat requires knoweldge about whether the node is in placement, i.e. expected to be functional.

2. Let independent monitoring/canary system actively probe healthcheck endpoint of every database node, determine whether the node is expected to be functional by comparing to M3DB placement data, and alert operator. Such solution would be ideal but has much higher cost.

**Does this PR introduce a user-facing and/or backwards incompatible change?**:

```release-note
NONE
```

**Does this PR require updating code package or user-facing documentation?**:

```documentation-note
NONE
```

### CODE REVIEW

**Review by andrewmains12 — COMMENTED** [review]
Lgtm in general! 

2 questions:

1. We're ok on cardinality here, right? I'm assuming cardinality is `num_client_nodes*num_db_nodes`--could get large in some cases.

2. Since we're emitting this metric at every client node, how do we plan to combine the metrics? I'm mostly thinking about cases where the clients don't agree (maybe one has stale data, for instance).

`sum dbnode_host | average`  maybe?

**Review by vdarulis — APPROVED** [review]
lgtm, although could we make this optional/configurable, if it's not too much effort?

**Review by vdarulis — APPROVED** [review]

**Comment by abliqo** [comment]
As discussed offline, this implementation will result in high cardinality of this metrics because it will be emitted from every m3db client and this client library connects to every m3db node in placement, so the number of combinations of emitter's `host` and node's `hostID` tag values will be significant. 
We could emit only failed health check results to reduce the cardinality during normal mode of operation, but if most nodes become unhealthy, the cardinality will be just as high and potentially cause cascading failures.

I am abandoning this PR in favor of another option discussed offline: emitting only the number of nodes down without the `hostID` tag. That way the maximum possible cardinality will not exceed number of clients. However, the operator will have to figure out which exactly node(s) unhealthy using separate tooling.

**Comment by abliqo** [comment]
Re-opening it. We can minimize the resulting cardinality by having client code pass a tally Scope without high-cardinality tags (the `host` tag in our case). That way, the cardinality will be limited by number of m3db nodes (tag `hostID`). We checked that we don't need to know the client's `host` for any of the metrics emitted by this client library.

**Review by prateek — APPROVED** [review]

**Pull request merged**
