### PR TITLE
[query] Fix query metrics assigning wrong status codes for errors

### PR DESCRIPTION
**Pull request by vpranckaitis**
**What this PR does / why we need it**:

Fixes cases where query error metrics don't match the response status code, e.g. error metric having `5xx` tag when the actual response code was 400. A function `xhttp.IsClientError()` was added that is used for deciding which error counter to increase. 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing and/or backwards incompatible change?**:

```release-note
NONE
```

**Does this PR require updating code package or user-facing documentation?**:

```documentation-note
NONE
```

### CODE REVIEW

**Review by linasm — COMMENTED** [review]
LGTM. I just wonder if there is any test coverage for this code?

**Comment by vpranckaitis** [comment]
> LGTM. I just wonder if there is any test coverage for this code?

Added some tests for `IsClientError()` (https://github.com/m3db/m3/pull/2960/commits/490e82564525cca8bd0c6c4a3f44a03435a6a8d6). As for testing metrics, the current code makes it quite inconvenient. I guess, a separate PR could be raised that would refactor metrics (introducing interfaces, dependency injection) in order to:
- make them more testable;
- reuse the same interface across multiple handlers (since the handlers in this PR mostly track identical metrics).

**Comment by linasm** [comment]
> > LGTM. I just wonder if there is any test coverage for this code?
> 
> Added some tests for `IsClientError()` ([490e825](https://github.com/m3db/m3/commit/490e82564525cca8bd0c6c4a3f44a03435a6a8d6)). As for testing metrics, the current code makes it quite inconvenient. I guess, a separate PR could be raised that would refactor metrics (introducing interfaces, dependency injection) in order to:
> 
> * make them more testable;
> * reuse the same interface across multiple handlers (since the handlers in this PR mostly track identical metrics).

I agree that testing the metrics can be complicated. Mainly brought this up because these metrics are widely used for alerting. Would appreciate @robskillington thoughts on how far we should go testing this.

**Review by robskillington — APPROVED** [review]
LGTM

**Comment by vpranckaitis** [comment]
Discussed this in person. It was mentioned that there should also be similar request metric tracking somewhere in the middleware. I'm merging this now to resolve existing issues. As a follow up, I will look into if it's possible to replace these with middleware metrics (or alternatively, if it makes sense to refactor these).

**Pull request merged**
