### PR TITLE
[coordinator] influxdb write endpoint: Return telegraf-compatible errors

### PR DESCRIPTION
**Pull request by fingon**
telegraf matches some specific substrings to detect if e.g.  metric is
outside retention range. So we provide those substrings.
**What this PR does / why we need it**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing and/or backwards incompatible change?**:

```release-note
NONE
```

**Does this PR require updating code package or user-facing documentation?**:

```documentation-note
NONE
```

### CODE REVIEW

**Comment by fingon** [comment]
I'm not super happy about how we detect the specific errors - a better way would be nice to have -  although this DOES work in our staging.

**Comment by fingon** [comment]
This doesn't work with rc9's more verbose messages probably. Closing for now.

**Comment by fingon** [comment]
Actually, as it turns out, it does work now that I tested it (some other branches of code produce similar but not matching strings but main ErrTooPast is still hit).

**Comment by robskillington** [comment]
Let me work out if we can do this in a more type safe way.. hm

**Comment by fingon** [comment]
This is clearly dead.

**Pull request closed without merging**
