### PR TITLE
[DOCS] Fix documentation links in m3query_intro.md

### PR DESCRIPTION
**Pull request by techtyler**
Documentation has moved to a generated site, using the links to the rendered site instead of relative path.

**What this PR does / why we need it**:

Fixes broken documentation links in m3query_intro.md.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing and/or backwards incompatible change?**:

```release-note
NONE
```

**Does this PR require updating code package or user-facing documentation?**:

```documentation-note
Only fixes documentation links.
```

### CODE REVIEW

**Review by wybczu — APPROVED** [review]
LGTM

**Comment by ChrisChinchilla** [comment]
@techtyler What is this file? it doesn't seem to be part of the docs and I am not sure if it actually even serves any purpose? So maybe it's better we just delete it, if there's content here we want to keep, it probably should be moved into the docs or readme

**Comment by techtyler** [comment]
@ChrisChinchilla It looks like you added this file in April of last year: https://github.com/m3db/m3/pull/3324/files#diff-7f1ca1a7b2c8304b3d0c8d6a1f6de9a5f059608e9a86d3d613e853aa81409d7c

If you don't think it is necessary, or should be moved to a new place, I'd be happy to help out. I just came across this by chance and noticed that the links were broken.

**Comment by ChrisChinchilla** [comment]
Huh @techtyler Good spot, I have no idea what it's doing here, so let's just remove it.

**Comment by techtyler** [comment]
Sounds good, but I can't approve it and I'm not sure if you can either so we might need someone else with write access to the repo to approve so we can merge.

**Review by ChrisChinchilla — APPROVED** [review]

**Pull request merged**
