### PR TITLE
Add documentation for systemd service

### PR DESCRIPTION
**Pull request by matejzero**
This is a proposed fix for #959.

Feel free to edit, since I'm not a native english speaker.

### CODE REVIEW

**Comment by prateek** [comment]
@schallert @nerd0 mind taking a look and reconciling with the example we have in the repo.

**Comment by matejzero** [comment]
I like @schallert's solution. It's a simple download & run solution. In my case you need to write the whole systemd service file:)

**Comment by prateek** [comment]
@matejzero awesome! if that addressed your concern, can we close this PR?

**Comment by matejzero** [comment]
Sure!

**Pull request closed without merging**
