### PR TITLE
[docs] Update docs to clarify Flush and Buffer in Storage Engine

### PR DESCRIPTION
**Pull request by asafm**
**What this PR does / why we need it**:
* Expand a bit about the type of flushes and how buffer is structured due to accommodate the two types of writes
* Emphasis few terms that were hard to read at first time
* Fixes several typos and punctuation.

### CODE REVIEW

**Comment by asafm** [comment]
I actually don't understand why the code coverage checks are failing since I haven't changed any code.

**Comment by asafm** [comment]
@ChrisChinchilla Can anyone take a look at this? I think it can really help new comers to the project

**Comment by ChrisChinchilla** [comment]
@asafm I am heads down getting our onboarding content overhauled and then I'll start looking at some of the smaller issues like this one, so bear with me, getting there :)

**Comment by asafm** [comment]
@ChrisChinchilla Should I resolve the conflicts, or you're still modifying that file more?

**Comment by ChrisChinchilla** [comment]
@asafm Now the restructure is live, I'll look at this tomorrow

**Comment by asafm** [comment]
@ChrisChinchilla Do you need me to merge from master?

**Comment by ChrisChinchilla** [comment]
@asafm Yes certainly, but you're going to find a LOT of conflicts, it might be easier to just take your changes and apply them to the relevant file in the new structure than solve all the conflicts. let me look now

**Review by ChrisChinchilla — APPROVED** [review]

**Comment by ChrisChinchilla** [comment]
Thanks @asafm !

**Pull request merged**
