### PR TITLE
Sharded object pool implementation

### PR DESCRIPTION
**Pull request by vdarulis**
**What this PR does / why we need it**:

Rewrite ObjectPool to support sharding the pool, to reduce lock contention.

```
name                                         old time/op    new time/op    delta
ObjectPoolGetPut                               72.1ns ± 3%    33.2ns ± 3%  -53.95%  (p=0.000 n=10+10)
ObjectPoolGetPut-6                             68.7ns ± 2%    32.7ns ± 1%  -52.39%  (p=0.000 n=10+10)
ObjectPoolGetPut-12                            68.6ns ± 2%    32.9ns ± 1%  -52.08%  (p=0.000 n=10+9)
ObjectPoolGetMultiPutContended                 2.29µs ± 2%    1.74µs ± 1%  -23.86%  (p=0.000 n=10+8)
ObjectPoolGetMultiPutContended-6               2.88µs ± 1%    1.38µs ± 1%  -51.93%  (p=0.000 n=10+9)
ObjectPoolGetMultiPutContended-12              3.88µs ± 2%    1.25µs ± 2%  -67.72%  (p=0.000 n=10+10)
ObjectPoolGetMultiPutContendedWithRefill       2.32µs ± 6%    2.10µs ± 2%   -9.45%  (p=0.000 n=10+10)
ObjectPoolGetMultiPutContendedWithRefill-6     3.07µs ± 3%    1.50µs ± 2%  -50.98%  (p=0.000 n=10+10)
ObjectPoolGetMultiPutContendedWithRefill-12    3.75µs ± 2%    1.38µs ± 7%  -63.12%  (p=0.000 n=10+10)
ObjectPoolParallel                             69.6ns ± 2%    35.1ns ± 2%  -49.61%  (p=0.000 n=10+10)
ObjectPoolParallel-6                            135ns ± 1%     118ns ± 1%  -12.60%  (p=0.000 n=9+10)
ObjectPoolParallel-12                           181ns ± 2%     132ns ± 1%  -27.28%  (p=0.000 n=9+9)

name                                         old alloc/op   new alloc/op   delta
ObjectPoolGetPut                                0.00B          0.00B          ~     (all equal)
ObjectPoolGetPut-6                              0.00B          0.00B          ~     (all equal)
ObjectPoolGetPut-12                             0.00B          0.00B          ~     (all equal)
ObjectPoolGetMultiPutContended                   512B ± 0%      515B ± 0%   +0.59%  (p=0.000 n=10+10)
ObjectPoolGetMultiPutContended-6                 512B ± 0%      517B ± 0%   +0.98%  (p=0.000 n=10+10)
ObjectPoolGetMultiPutContended-12                512B ± 0%      518B ± 0%   +1.17%  (p=0.000 n=10+10)
ObjectPoolGetMultiPutContendedWithRefill         512B ± 0%      618B ± 0%  +20.70%  (p=0.000 n=10+8)
ObjectPoolGetMultiPutContendedWithRefill-6       596B ± 1%      721B ± 0%  +20.96%  (p=0.000 n=10+10)
ObjectPoolGetMultiPutContendedWithRefill-12      666B ± 1%      724B ± 0%   +8.72%  (p=0.000 n=10+10)
ObjectPoolParallel                              0.00B          0.00B          ~     (all equal)
ObjectPoolParallel-6                            0.00B          0.00B          ~     (all equal)
ObjectPoolParallel-12                           0.00B          0.00B          ~     (all equal)

name                                         old allocs/op  new allocs/op  delta
ObjectPoolGetPut                                 0.00           0.00          ~     (all equal)
ObjectPoolGetPut-6                               0.00           0.00          ~     (all equal)
ObjectPoolGetPut-12                              0.00           0.00          ~     (all equal)
ObjectPoolGetMultiPutContended                   16.0 ± 0%      16.0 ± 0%     ~     (all equal)
ObjectPoolGetMultiPutContended-6                 16.0 ± 0%      16.0 ± 0%     ~     (all equal)
ObjectPoolGetMultiPutContended-12                16.0 ± 0%      16.0 ± 0%     ~     (all equal)
ObjectPoolGetMultiPutContendedWithRefill         16.0 ± 0%      19.0 ± 0%  +18.75%  (p=0.000 n=10+10)
ObjectPoolGetMultiPutContendedWithRefill-6       18.0 ± 0%      22.0 ± 0%  +22.22%  (p=0.000 n=10+10)
ObjectPoolGetMultiPutContendedWithRefill-12      20.0 ± 0%      22.0 ± 0%  +10.00%  (p=0.000 n=10+10)
ObjectPoolParallel                               0.00           0.00          ~     (all equal)
ObjectPoolParallel-6                             0.00           0.00          ~     (all equal)
ObjectPoolParallel-12                            0.00           0.00          ~     (all equal)
```

**Special notes for your reviewer**:

**Does this PR introduce a user-facing and/or backwards incompatible change?**:

```release-note
Add configuration option to tune number of shards for object pools
```

**Does this PR require updating code package or user-facing documentation?**:

```documentation-note

```

### CODE REVIEW

**Comment by robskillington** [comment]
Have you tested with CPUID instruction call and selecting the "right shard" for your CPU (you still need a lock/unlock but it's more likely to pick an uncontested queue since goroutines rarely get moved about)

**Comment by vdarulis** [comment]
> Have you tested with CPUID instruction call and selecting the "right shard" for your CPU (you still need a lock/unlock but it's more likely to pick an uncontested queue since goroutines rarely get moved about)
Not yet, will poke around more whenever I have more spare cycles - the improvement for contended cases is less than I've hoped, refactoring this into smaller, incremental improvements.

**Comment by robskillington** [comment]
@vdarulis can find the CPUID assembly code here if interested in repurposing it for this kind of an object pool, I know @prateek and I had a look at it briefly when investigating sharded object pools but did not have the chance to test it.
https://github.com/jonhoo/drwmutex

**Comment by vdarulis** [comment]
Closing this as I cannot compete with sync.Pool without primitives the runtime has :(
Striping gives little benefit and more complexity in pool sizing, etc.

**Pull request closed without merging**
