### PR TITLE
[WIP] - Allow dynamic configuration injection

### PR DESCRIPTION
**Pull request by nerd0**
**What this PR does / why we need it**:

Fixes # [1820](https://github.com/m3db/m3/issues/1820)

**Special notes for your reviewer**:

**Does this PR introduce a user-facing and/or backwards incompatible change?**:

None

```release-note
Componentize main files to allow dynamic configuration injection
```

**Does this PR require updating code package or user-facing documentation?**:

None

```documentation-note

```

### CODE REVIEW

**Comment by robskillington** [comment]
Hey @nerd0 so for the DB node all you need to do is call `server.Run(server.RunOptions{Config: yourCfg})` for dynamic configuration.

Can we simply make the aggregator follow the same model (use a `server` package and allow passing the config by a struct in the options) instead of adding another layer of indirection to both of these (otherwise there would be two levels of indirection in the dbnode main/server).

**Comment by nerd0** [comment]
> Very keen to see #1820 go ahead.
> 
> Quick one for the DB node all you need to do is call `server.Run(server.RunOptions{Config: yourCfg})` for dynamic configuration.
> 
> Can we simply make the aggregator follow the same model (use a `server` package and allow passing the config by a struct in the options) instead of adding another layer of indirection to both of these (otherwise there would be two levels of indirection in the dbnode main/server).

Fair points, the idea with this approach was to ensure that the main file logic doesn't drift too far from the "vanilla" invocation of these services. The aggregator and dbnode main files differ quite a bit thus any main files maintained outside of the m3 repository will require a lot of duplicated code while also ensuring that any changes are propagated.

**Comment by robskillington** [comment]
Nice, looks good after the changes! (Also, just as a maybe "out of my jurisdiction" request and hence maybe not worth making, it would be really amazing if people did not use a different main file outside of the open source repo to run parts of their production stack. We did this for a significant amount of time and was super hard to finally migrate it back to fully open source and have the build be 1-1 binary of what is in open source, and hence make it possible to debug the same binary one person has as another)

**Comment by nerd0** [comment]
> Nice, looks good after the changes! (Also, just as a maybe "out of my jurisdiction" request and hence maybe not worth making, it would be really amazing if people did not use a different main file outside of the open source repo to run parts of their production stack. We did this for a significant amount of time and was super hard to finally migrate it back to fully open source and have the build be 1-1 binary of what is in open source, and hence make it possible to debug the same binary one person has as another)

Agreed with your comment, however the `cluster` package is tightly coupled to the ETCD client. Perhaps the better solution for this is too rewrite the `cluster` package to either allow for dynamic configuration injection rather than just static configuration files. Another option would be to rewrite the `cluster` package to allow for different discovery backends to be used. 

This diff was pretty much abandon on the last commit due to assumptions about how `main.go` was structured for the aggregator and the refactoring of the integration tests package.

**Pull request closed without merging**
