### PR TITLE
[linter] Fix linter not finding any issues

### PR DESCRIPTION
**Pull request by vpranckaitis**
**What this PR does / why we need it**:

Fixes linter not producing any errors. 

For some unknown reason, linting doesn't work when setting `new-from-rev` to https://github.com/m3db/m3/commit/5edd3f1c47a41e1df834f92b0ab062206a9e951a or any revision before it ([see buildkite](https://buildkite.com/uberopensource/m3-monorepo-public/builds/5534#fa3b74c1-6e41-4c95-bcce-047777bdb914)), but it start working when switching to https://github.com/m3db/m3/commit/cc7822453e789be822047de096d30e31780acdc7 ([see buildkite](https://buildkite.com/uberopensource/m3-monorepo-public/builds/5535#9e5b8fa8-f246-42d0-baa7-7c7804b2d722)).

Since quite a few linting errors have creeped in during this time, I'm gonna set `new-from-rev` to most recent commit on `master`. 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing and/or backwards incompatible change?**:

```release-note
NONE
```

**Does this PR require updating code package or user-facing documentation?**:

```documentation-note
NONE
```

### CODE REVIEW

**Review by linasm — APPROVED** [review]
Approving as it makes at least the current issue go away.
However we have not understood the root cause yet, so I'm afraid the linter might just stop working after some number of commits again.
Tagging @vdarulis and @robskillington maybe they have some idea about what's going on.

**Comment by vpranckaitis** [comment]
In case it helps, a description of what debugging I did:
- taking a recent `master` and trying various `new-from-rev` commits (see the commits in PR description for the boundary where it stopped working);
- checking out older revision `X` of the repo. Creating (without commiting) a go file with lint errors. At first the errors from the file don't appear on `make lint`, but they start appearing once `new-from-rev` is changed to `X` or  parent of `X`.

Could this be a problem related to big diffs between `new-from-rev` and current commit? In the golangci's [FAQ they mention using something like](https://golangci-lint.run/usage/faq/#how-to-integrate-golangci-lint-into-large-project-with-thousands-of-issues) `new-from-rev: HEAD~1` – maybe it doesn't support long histories or the functionality is not well tested on bigger commit history / bigger projects?

**Comment by linasm** [comment]
Yeah, `new-from-rev: HEAD~<n>` would only work with some big enough `<n>` for the cases when someone has multiple commits on their branch (and is hacky).
@vpranckaitis please try `new-from-rev: master`

**Comment by vpranckaitis** [comment]
`master` works. Though I believe it would make the lint steps on CI master builds no-op — probably not an issue for this repo, since before merging a PR has to be up-to-date with master

**Comment by linasm** [comment]
Yeah, running the linter on PR builds is exactly what we need. I see no point in running it on master post-merge.

**Comment by vdarulis** [comment]
> Yeah, running the linter on PR builds is exactly what we need. I see no point in running it on master post-merge.

no idea why new-from-rev wouldn't work, but I haven't used the setting myself in practice. +1 on just running on PRs if that fixes it.

**Review by vdarulis — APPROVED** [review]

**Pull request merged**
