### PR TITLE
[WIP] Shard Tick/Write race

### PR DESCRIPTION
**Pull request by prateek**
Wrote up a test that inserts and ticks at the same time. Can get it to hang after a few iterations of execution. Not sure what the issue: bad test setup / code race ?

### CODE REVIEW

**Comment by robskillington** [comment]
Hm interesting, I can dig in here.

**Comment by richardartoul** [comment]
@prateek didn't we resolve this?

**Comment by prateek** [comment]
@richardartoul Nah, we resolved a couple of races during concurrent Read/Tick; but there's something funky going on during concurrent Write/Tick as well - the attached test fails periodically.

**Comment by robskillington** [comment]
As per https://github.com/m3db/m3/pull/2128 this can finally be closed, yay!

**Pull request closed without merging**
